"""JSON Schema Input Adapter (production-quality for v1).

Converts a JSON Schema document (supplied as a parsed Python dict) into a
CanonicalSchema.  Uses only the Python standard library — no external
JSON Schema validator library is required (RL-08: safe structured parsing
with explicit dict access, no eval/exec).

Supported JSON Schema constructs:
  - type: string | integer | number | boolean | null | object | array
  - properties (object fields, recursive)
  - items (array element type, recursive)
  - required (list of required property names)
  - title, description
  - enum, pattern, minLength, maxLength, minimum, maximum
  - $defs / definitions (shallow inline resolution — no full $ref graph)
  - allOf with a single entry (common pattern for descriptions in drafts 4-7)
  - Nested objects and arrays to arbitrary depth

Not in scope for v1 (stubs excluded, not silently dropped):
  - Full $ref graph resolution across external URIs
  - anyOf / oneOf / if-then-else
  - OpenAPI-specific extensions

Stable ID generation:
  Path-based deterministic IDs are generated by hashing the canonical path
  string with SHA-256 and taking a 16-char hex prefix.  Given the same
  schema, the same field always gets the same ID regardless of insertion
  order — satisfying the determinism constraint.
"""

from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Set, Tuple

from packages.adapters.base import AdapterMetadata, AdapterParseError, InputSchemaAdapter
from packages.core.models.canonical_schema import (
    CanonicalField,
    CanonicalSchema,
    Cardinality,
    FieldConstraints,
    FieldType,
    FieldTypeCategory,
    TerminologyReference,
)

# JSON Schema type -> canonical primitive name mapping.
# Open-ended: adapters may produce any primitive string; this mapping covers
# the standard types without hardcoding any domain standard (RL-03).
_JS_TYPE_TO_PRIMITIVE: Dict[str, str] = {
    "string": "string",
    "integer": "integer",
    "number": "decimal",
    "boolean": "boolean",
    "null": "null",
}


def _stable_field_id(path: str) -> str:
    """Produce a stable, deterministic ID from a canonical field path.

    Uses SHA-256 so the ID is collision-resistant and path-dependent.
    """
    digest = hashlib.sha256(path.encode("utf-8")).hexdigest()
    return digest[:24]


def _resolve_ref(ref: str, defs: Dict[str, Any], schema_root: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Shallow $ref resolution within the same document.

    Only handles '#/$defs/Name' and '#/definitions/Name' patterns.
    External URI refs are out of scope for v1.
    """
    if not ref.startswith("#/"):
        return None
    parts = ref.lstrip("#/").split("/")
    node: Any = schema_root
    for part in parts:
        if not isinstance(node, dict):
            return None
        node = node.get(part)
    return node if isinstance(node, dict) else None


class JsonSchemaAdapter(InputSchemaAdapter):
    """Converts a JSON Schema dict into a CanonicalSchema."""

    FORMAT_ID = "json_schema"

    def __init__(self) -> None:
        self._meta = AdapterMetadata(
            adapter_id="json_schema_adapter_v1",
            display_name="JSON Schema Adapter",
            version="1.0.0",
            supported_formats=[self.FORMAT_ID],
            description="Parses JSON Schema (draft 4/6/7/2019/2020) into the canonical schema model.",
        )

    @property
    def metadata(self) -> AdapterMetadata:
        return self._meta

    def parse(
        self,
        raw_input: Any,
        schema_name: str = "",
        schema_version: str = "",
    ) -> CanonicalSchema:
        """Parse a JSON Schema dict into a CanonicalSchema.

        Args:
            raw_input: A Python dict representing the JSON Schema document.
            schema_name: Override the schema name (falls back to schema title).
            schema_version: Override the schema version.

        Raises:
            AdapterParseError: If raw_input is not a dict or is structurally invalid.
        """
        if not isinstance(raw_input, dict):
            raise AdapterParseError(
                f"JsonSchemaAdapter expects a dict; received {type(raw_input).__name__}"
            )

        # Collect $defs / definitions for shallow $ref resolution
        defs: Dict[str, Any] = {}
        defs.update(raw_input.get("$defs", {}))
        defs.update(raw_input.get("definitions", {}))

        name = schema_name or raw_input.get("title", "")
        version = schema_version or raw_input.get("$schema", "")

        fields: List[CanonicalField] = []
        seen_paths: Set[str] = set()

        self._walk_schema(
            node=raw_input,
            path="",
            required_set=set(raw_input.get("required", [])),
            fields=fields,
            seen_paths=seen_paths,
            defs=defs,
            schema_root=raw_input,
        )

        return CanonicalSchema(
            id=str(uuid.uuid4()),
            name=name,
            version=version,
            description=raw_input.get("description"),
            fields=fields,
            created_at=datetime.now(timezone.utc).isoformat(),
        )

    def _walk_schema(
        self,
        node: Dict[str, Any],
        path: str,
        required_set: Set[str],
        fields: List[CanonicalField],
        seen_paths: Set[str],
        defs: Dict[str, Any],
        schema_root: Dict[str, Any],
    ) -> None:
        """Recursively walk a JSON Schema node and emit CanonicalFields.

        Only object properties are visited recursively; primitives and arrays
        produce leaf fields.
        """
        # Resolve allOf with a single entry (used for descriptions in some drafts)
        if "allOf" in node and len(node.get("allOf", [])) == 1:
            merged = {**node["allOf"][0], **{k: v for k, v in node.items() if k != "allOf"}}
            node = merged

        # Follow $ref if present (shallow, same-document only)
        if "$ref" in node:
            resolved = _resolve_ref(node["$ref"], defs, schema_root)
            if resolved:
                # Merge: local keys override ref keys
                node = {**resolved, **{k: v for k, v in node.items() if k != "$ref"}}

        node_type = node.get("type")
        properties = node.get("properties", {})

        if node_type == "object" or (properties and node_type is None):
            req = set(node.get("required", []))
            for prop_name, prop_schema in properties.items():
                child_path = f"{path}.{prop_name}" if path else prop_name
                self._walk_property(
                    prop_name=prop_name,
                    prop_schema=prop_schema if isinstance(prop_schema, dict) else {},
                    path=child_path,
                    is_required=prop_name in required_set or prop_name in req,
                    fields=fields,
                    seen_paths=seen_paths,
                    defs=defs,
                    schema_root=schema_root,
                )
        elif path:
            # Root is not an object — emit a single field for the root itself
            field = self._make_field(
                path=path,
                node=node,
                is_required=False,
                defs=defs,
                schema_root=schema_root,
            )
            if field and path not in seen_paths:
                seen_paths.add(path)
                fields.append(field)

    def _walk_property(
        self,
        prop_name: str,
        prop_schema: Dict[str, Any],
        path: str,
        is_required: bool,
        fields: List[CanonicalField],
        seen_paths: Set[str],
        defs: Dict[str, Any],
        schema_root: Dict[str, Any],
    ) -> None:
        """Emit a field for this property, then recurse if it's an object."""
        # Resolve $ref
        if "$ref" in prop_schema:
            resolved = _resolve_ref(prop_schema["$ref"], defs, schema_root)
            if resolved:
                prop_schema = {**resolved, **{k: v for k, v in prop_schema.items() if k != "$ref"}}

        # Resolve allOf with single entry
        if "allOf" in prop_schema and len(prop_schema.get("allOf", [])) == 1:
            merged = {**prop_schema["allOf"][0], **{k: v for k, v in prop_schema.items() if k != "allOf"}}
            prop_schema = merged

        prop_type = prop_schema.get("type")
        has_properties = bool(prop_schema.get("properties"))

        if prop_type == "object" or (has_properties and prop_type is None):
            # Emit an OBJECT field for the parent, then recurse into children
            if path not in seen_paths:
                seen_paths.add(path)
                fields.append(
                    CanonicalField(
                        id=_stable_field_id(path),
                        path=path,
                        field_type=FieldType(category=FieldTypeCategory.OBJECT),
                        cardinality=Cardinality(min_occurs=1 if is_required else 0, max_occurs=1),
                        label=prop_schema.get("title"),
                        description=prop_schema.get("description"),
                        constraints=FieldConstraints(required=is_required),
                        metadata_tags={},
                    )
                )
            child_req = set(prop_schema.get("required", []))
            for child_name, child_schema in prop_schema.get("properties", {}).items():
                child_path = f"{path}.{child_name}"
                self._walk_property(
                    prop_name=child_name,
                    prop_schema=child_schema if isinstance(child_schema, dict) else {},
                    path=child_path,
                    is_required=child_name in child_req,
                    fields=fields,
                    seen_paths=seen_paths,
                    defs=defs,
                    schema_root=schema_root,
                )
        else:
            field = self._make_field(
                path=path,
                node=prop_schema,
                is_required=is_required,
                defs=defs,
                schema_root=schema_root,
            )
            if field and path not in seen_paths:
                seen_paths.add(path)
                fields.append(field)

    def _make_field(
        self,
        path: str,
        node: Dict[str, Any],
        is_required: bool,
        defs: Dict[str, Any],
        schema_root: Dict[str, Any],
    ) -> Optional[CanonicalField]:
        """Build a CanonicalField for a leaf or array schema node."""
        node_type = node.get("type")

        if node_type == "array":
            items = node.get("items", {})
            if "$ref" in items:
                resolved = _resolve_ref(items["$ref"], defs, schema_root)
                if resolved:
                    items = resolved
            items_ft = self._resolve_field_type(items)
            field_type = FieldType(
                category=FieldTypeCategory.ARRAY,
                items_type=items_ft,
            )
        else:
            field_type = self._resolve_field_type(node)

        constraints = self._build_constraints(node, is_required)
        terminology_refs = self._build_terminology_refs(node)

        # Cardinality: array fields default to 0..* unless required (1..*)
        if node_type == "array":
            cardinality = Cardinality(
                min_occurs=1 if is_required else 0,
                max_occurs=None,
            )
        else:
            cardinality = Cardinality(
                min_occurs=1 if is_required else 0,
                max_occurs=1,
            )

        return CanonicalField(
            id=_stable_field_id(path),
            path=path,
            field_type=field_type,
            cardinality=cardinality,
            label=node.get("title"),
            description=node.get("description"),
            constraints=constraints,
            terminology_references=terminology_refs,
            metadata_tags={},
        )

    @staticmethod
    def _resolve_field_type(node: Dict[str, Any]) -> FieldType:
        """Map a JSON Schema node's type to a CanonicalFieldType."""
        node_type = node.get("type", "string")
        if node_type == "object":
            return FieldType(category=FieldTypeCategory.OBJECT)
        if node_type == "array":
            return FieldType(category=FieldTypeCategory.ARRAY)
        primitive = _JS_TYPE_TO_PRIMITIVE.get(node_type, node_type)
        if node.get("format"):
            # Use format hint as a more precise primitive name if meaningful
            fmt = node["format"]
            if fmt in ("date", "date-time", "time", "uri", "email", "uuid"):
                primitive = fmt.replace("-", "")  # "date-time" -> "datetime"
        return FieldType(category=FieldTypeCategory.PRIMITIVE, primitive=primitive)

    @staticmethod
    def _build_constraints(node: Dict[str, Any], is_required: bool) -> FieldConstraints:
        enums = node.get("enum")
        return FieldConstraints(
            required=is_required,
            enums=[str(e) for e in enums] if enums is not None else None,
            pattern=node.get("pattern"),
            min_value=node.get("minimum") if node.get("minimum") is not None else node.get("exclusiveMinimum"),
            max_value=node.get("maximum") if node.get("maximum") is not None else node.get("exclusiveMaximum"),
            min_length=node.get("minLength"),
            max_length=node.get("maxLength"),
        )

    @staticmethod
    def _build_terminology_refs(node: Dict[str, Any]) -> List[TerminologyReference]:
        """Extract any vocabulary/terminology hints present in the node."""
        refs: List[TerminologyReference] = []
        # x-terminology is a non-standard extension for tools that annotate schemas
        if "x-terminology" in node:
            term = node["x-terminology"]
            if isinstance(term, dict) and "system" in term:
                refs.append(
                    TerminologyReference(
                        system=term["system"],
                        code=term.get("code"),
                        display=term.get("display"),
                    )
                )
        return refs
