/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * v1 REST API for the Healthcare Data Mapping Tool.
Auth: Pass X-User-Id and X-User-Role headers with every request.
Roles: viewer, analyst, approver, admin.

 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CatalogSchemaResponse,
  CatalogVersionResponse,
  CreateMappingVersionRequest,
  CreateProjectRequest,
  ExportMappingParams,
  ExportResponse,
  HTTPValidationError,
  ImportSourceSchemaRequest,
  ListCatalogSchemasParams,
  MappingVersionResponse,
  PinnedSchemaRef,
  ProjectResponse,
  ProjectSchemasResponse,
  SelectTargetSchemaRequest,
  SuggestionsRequest,
  SuggestionsResponse,
  UpdateProjectStatusRequest,
  ValidateRequest,
  ValidationResponse,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create Project
 */
export const getCreateProjectUrl = () => {
  return `/projects`;
};

export const createProject = async (
  createProjectRequest: CreateProjectRequest,
  options?: RequestInit,
): Promise<ProjectResponse> => {
  return customFetch<ProjectResponse>(getCreateProjectUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createProjectRequest),
  });
};

export const getCreateProjectMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProject>>,
    TError,
    { data: BodyType<CreateProjectRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProject>>,
  TError,
  { data: BodyType<CreateProjectRequest> },
  TContext
> => {
  const mutationKey = ["createProject"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProject>>,
    { data: BodyType<CreateProjectRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createProject(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProjectMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProject>>
>;
export type CreateProjectMutationBody = BodyType<CreateProjectRequest>;
export type CreateProjectMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Create Project
 */
export const useCreateProject = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProject>>,
    TError,
    { data: BodyType<CreateProjectRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createProject>>,
  TError,
  { data: BodyType<CreateProjectRequest> },
  TContext
> => {
  return useMutation(getCreateProjectMutationOptions(options));
};

/**
 * @summary List Projects
 */
export const getListProjectsUrl = () => {
  return `/projects`;
};

export const listProjects = async (
  options?: RequestInit,
): Promise<ProjectResponse[]> => {
  return customFetch<ProjectResponse[]>(getListProjectsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListProjectsQueryKey = () => {
  return [`/projects`] as const;
};

export const getListProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof listProjects>>,
  TError = ErrorType<HTTPValidationError>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listProjects>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListProjectsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjects>>> = ({
    signal,
  }) => listProjects({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listProjects>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listProjects>>
>;
export type ListProjectsQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary List Projects
 */

export function useListProjects<
  TData = Awaited<ReturnType<typeof listProjects>>,
  TError = ErrorType<HTTPValidationError>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listProjects>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListProjectsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Project
 */
export const getGetProjectUrl = (projectId: string) => {
  return `/projects/${projectId}`;
};

export const getProject = async (
  projectId: string,
  options?: RequestInit,
): Promise<ProjectResponse> => {
  return customFetch<ProjectResponse>(getGetProjectUrl(projectId), {
    ...options,
    method: "GET",
  });
};

export const getGetProjectQueryKey = (projectId: string) => {
  return [`/projects/${projectId}`] as const;
};

export const getGetProjectQueryOptions = <
  TData = Awaited<ReturnType<typeof getProject>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProject>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProjectQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProject>>> = ({
    signal,
  }) => getProject(projectId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProject>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProjectQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProject>>
>;
export type GetProjectQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary Get Project
 */

export function useGetProject<
  TData = Awaited<ReturnType<typeof getProject>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProject>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetProjectQueryOptions(projectId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update Project Status
 */
export const getUpdateProjectStatusUrl = (projectId: string) => {
  return `/projects/${projectId}`;
};

export const updateProjectStatus = async (
  projectId: string,
  updateProjectStatusRequest: UpdateProjectStatusRequest,
  options?: RequestInit,
): Promise<ProjectResponse> => {
  return customFetch<ProjectResponse>(getUpdateProjectStatusUrl(projectId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProjectStatusRequest),
  });
};

export const getUpdateProjectStatusMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProjectStatus>>,
    TError,
    { projectId: string; data: BodyType<UpdateProjectStatusRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProjectStatus>>,
  TError,
  { projectId: string; data: BodyType<UpdateProjectStatusRequest> },
  TContext
> => {
  const mutationKey = ["updateProjectStatus"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProjectStatus>>,
    { projectId: string; data: BodyType<UpdateProjectStatusRequest> }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return updateProjectStatus(projectId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProjectStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProjectStatus>>
>;
export type UpdateProjectStatusMutationBody =
  BodyType<UpdateProjectStatusRequest>;
export type UpdateProjectStatusMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Update Project Status
 */
export const useUpdateProjectStatus = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProjectStatus>>,
    TError,
    { projectId: string; data: BodyType<UpdateProjectStatusRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateProjectStatus>>,
  TError,
  { projectId: string; data: BodyType<UpdateProjectStatusRequest> },
  TContext
> => {
  return useMutation(getUpdateProjectStatusMutationOptions(options));
};

/**
 * Import a source schema via the adapter registry, register in catalog, pin to project.
 * @summary Import Source Schema
 */
export const getImportSourceSchemaUrl = (projectId: string) => {
  return `/projects/${projectId}/schemas/source/import`;
};

export const importSourceSchema = async (
  projectId: string,
  importSourceSchemaRequest: ImportSourceSchemaRequest,
  options?: RequestInit,
): Promise<PinnedSchemaRef> => {
  return customFetch<PinnedSchemaRef>(getImportSourceSchemaUrl(projectId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(importSourceSchemaRequest),
  });
};

export const getImportSourceSchemaMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importSourceSchema>>,
    TError,
    { projectId: string; data: BodyType<ImportSourceSchemaRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof importSourceSchema>>,
  TError,
  { projectId: string; data: BodyType<ImportSourceSchemaRequest> },
  TContext
> => {
  const mutationKey = ["importSourceSchema"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof importSourceSchema>>,
    { projectId: string; data: BodyType<ImportSourceSchemaRequest> }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return importSourceSchema(projectId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ImportSourceSchemaMutationResult = NonNullable<
  Awaited<ReturnType<typeof importSourceSchema>>
>;
export type ImportSourceSchemaMutationBody =
  BodyType<ImportSourceSchemaRequest>;
export type ImportSourceSchemaMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Import Source Schema
 */
export const useImportSourceSchema = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importSourceSchema>>,
    TError,
    { projectId: string; data: BodyType<ImportSourceSchemaRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof importSourceSchema>>,
  TError,
  { projectId: string; data: BodyType<ImportSourceSchemaRequest> },
  TContext
> => {
  return useMutation(getImportSourceSchemaMutationOptions(options));
};

/**
 * Pin an already-registered catalog schema as the target for this project.
 * @summary Select Target Schema
 */
export const getSelectTargetSchemaUrl = (projectId: string) => {
  return `/projects/${projectId}/schemas/target/select`;
};

export const selectTargetSchema = async (
  projectId: string,
  selectTargetSchemaRequest: SelectTargetSchemaRequest,
  options?: RequestInit,
): Promise<PinnedSchemaRef> => {
  return customFetch<PinnedSchemaRef>(getSelectTargetSchemaUrl(projectId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(selectTargetSchemaRequest),
  });
};

export const getSelectTargetSchemaMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof selectTargetSchema>>,
    TError,
    { projectId: string; data: BodyType<SelectTargetSchemaRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof selectTargetSchema>>,
  TError,
  { projectId: string; data: BodyType<SelectTargetSchemaRequest> },
  TContext
> => {
  const mutationKey = ["selectTargetSchema"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof selectTargetSchema>>,
    { projectId: string; data: BodyType<SelectTargetSchemaRequest> }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return selectTargetSchema(projectId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SelectTargetSchemaMutationResult = NonNullable<
  Awaited<ReturnType<typeof selectTargetSchema>>
>;
export type SelectTargetSchemaMutationBody =
  BodyType<SelectTargetSchemaRequest>;
export type SelectTargetSchemaMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Select Target Schema
 */
export const useSelectTargetSchema = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof selectTargetSchema>>,
    TError,
    { projectId: string; data: BodyType<SelectTargetSchemaRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof selectTargetSchema>>,
  TError,
  { projectId: string; data: BodyType<SelectTargetSchemaRequest> },
  TContext
> => {
  return useMutation(getSelectTargetSchemaMutationOptions(options));
};

/**
 * Return pinned source and target schema references for a project.
 * @summary Get Project Schemas
 */
export const getGetProjectSchemasUrl = (projectId: string) => {
  return `/projects/${projectId}/schemas`;
};

export const getProjectSchemas = async (
  projectId: string,
  options?: RequestInit,
): Promise<ProjectSchemasResponse> => {
  return customFetch<ProjectSchemasResponse>(
    getGetProjectSchemasUrl(projectId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetProjectSchemasQueryKey = (projectId: string) => {
  return [`/projects/${projectId}/schemas`] as const;
};

export const getGetProjectSchemasQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectSchemas>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProjectSchemas>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectSchemasQueryKey(projectId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectSchemas>>
  > = ({ signal }) =>
    getProjectSchemas(projectId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectSchemas>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProjectSchemasQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectSchemas>>
>;
export type GetProjectSchemasQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary Get Project Schemas
 */

export function useGetProjectSchemas<
  TData = Awaited<ReturnType<typeof getProjectSchemas>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProjectSchemas>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetProjectSchemasQueryOptions(projectId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Generate TOP-K mapping suggestions for every target field.
 * @summary Get Suggestions
 */
export const getGetSuggestionsUrl = (projectId: string) => {
  return `/projects/${projectId}/suggestions`;
};

export const getSuggestions = async (
  projectId: string,
  suggestionsRequest: SuggestionsRequest,
  options?: RequestInit,
): Promise<SuggestionsResponse> => {
  return customFetch<SuggestionsResponse>(getGetSuggestionsUrl(projectId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(suggestionsRequest),
  });
};

export const getGetSuggestionsMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getSuggestions>>,
    TError,
    { projectId: string; data: BodyType<SuggestionsRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getSuggestions>>,
  TError,
  { projectId: string; data: BodyType<SuggestionsRequest> },
  TContext
> => {
  const mutationKey = ["getSuggestions"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getSuggestions>>,
    { projectId: string; data: BodyType<SuggestionsRequest> }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return getSuggestions(projectId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetSuggestionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof getSuggestions>>
>;
export type GetSuggestionsMutationBody = BodyType<SuggestionsRequest>;
export type GetSuggestionsMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Get Suggestions
 */
export const useGetSuggestions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getSuggestions>>,
    TError,
    { projectId: string; data: BodyType<SuggestionsRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof getSuggestions>>,
  TError,
  { projectId: string; data: BodyType<SuggestionsRequest> },
  TContext
> => {
  return useMutation(getGetSuggestionsMutationOptions(options));
};

/**
 * @summary Create Mapping Version
 */
export const getCreateMappingVersionUrl = (projectId: string) => {
  return `/projects/${projectId}/mappings`;
};

export const createMappingVersion = async (
  projectId: string,
  createMappingVersionRequest: CreateMappingVersionRequest,
  options?: RequestInit,
): Promise<MappingVersionResponse> => {
  return customFetch<MappingVersionResponse>(
    getCreateMappingVersionUrl(projectId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createMappingVersionRequest),
    },
  );
};

/**
 * @summary Update Mapping Version
 */
export const getUpdateMappingVersionUrl = (projectId: string, versionId: string) => {
  return `/projects/${projectId}/mappings/${versionId}`;
};

export const updateMappingVersion = async (
  projectId: string,
  versionId: string,
  updateMappingVersionRequest: UpdateMappingVersionRequest,
  options?: RequestInit,
): Promise<MappingVersionResponse> => {
  return customFetch<MappingVersionResponse>(
    getUpdateMappingVersionUrl(projectId, versionId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateMappingVersionRequest),
    },
  );
};

export const getUpdateMappingVersionMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMappingVersion>>,
    TError,
    { projectId: string; versionId: string; data: BodyType<UpdateMappingVersionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMappingVersion>>,
  TError,
  { projectId: string; versionId: string; data: BodyType<UpdateMappingVersionRequest> },
  TContext
> => {
  const mutationKey = ["updateMappingVersion"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMappingVersion>>,
    { projectId: string; versionId: string; data: BodyType<UpdateMappingVersionRequest> }
  > = (props) => {
    const { projectId, versionId, data } = props ?? {};
    return updateMappingVersion(projectId, versionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMappingVersionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMappingVersion>>
>;
export type UpdateMappingVersionMutationBody = BodyType<UpdateMappingVersionRequest>;
export type UpdateMappingVersionMutationError = ErrorType<HTTPValidationError>;

export const useUpdateMappingVersion = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMappingVersion>>,
    TError,
    { projectId: string; versionId: string; data: BodyType<UpdateMappingVersionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateMappingVersion>>,
  TError,
  { projectId: string; versionId: string; data: BodyType<UpdateMappingVersionRequest> },
  TContext
> => {
  return useMutation(getUpdateMappingVersionMutationOptions(options));
};

export const getCreateMappingVersionMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMappingVersion>>,
    TError,
    { projectId: string; data: BodyType<CreateMappingVersionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMappingVersion>>,
  TError,
  { projectId: string; data: BodyType<CreateMappingVersionRequest> },
  TContext
> => {
  const mutationKey = ["createMappingVersion"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMappingVersion>>,
    { projectId: string; data: BodyType<CreateMappingVersionRequest> }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return createMappingVersion(projectId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMappingVersionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createMappingVersion>>
>;
export type CreateMappingVersionMutationBody =
  BodyType<CreateMappingVersionRequest>;
export type CreateMappingVersionMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Create Mapping Version
 */
export const useCreateMappingVersion = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMappingVersion>>,
    TError,
    { projectId: string; data: BodyType<CreateMappingVersionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createMappingVersion>>,
  TError,
  { projectId: string; data: BodyType<CreateMappingVersionRequest> },
  TContext
> => {
  return useMutation(getCreateMappingVersionMutationOptions(options));
};

/**
 * @summary List Mapping Versions
 */
export const getListMappingVersionsUrl = (projectId: string) => {
  return `/projects/${projectId}/mappings`;
};

export const listMappingVersions = async (
  projectId: string,
  options?: RequestInit,
): Promise<MappingVersionResponse[]> => {
  return customFetch<MappingVersionResponse[]>(
    getListMappingVersionsUrl(projectId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getListMappingVersionsQueryKey = (projectId: string) => {
  return [`/projects/${projectId}/mappings`] as const;
};

export const getListMappingVersionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMappingVersions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMappingVersions>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListMappingVersionsQueryKey(projectId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listMappingVersions>>
  > = ({ signal }) =>
    listMappingVersions(projectId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listMappingVersions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListMappingVersionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMappingVersions>>
>;
export type ListMappingVersionsQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary List Mapping Versions
 */

export function useListMappingVersions<
  TData = Awaited<ReturnType<typeof listMappingVersions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMappingVersions>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMappingVersionsQueryOptions(projectId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Mapping Version
 */
export const getGetMappingVersionUrl = (
  projectId: string,
  versionId: string,
) => {
  return `/projects/${projectId}/mappings/${versionId}`;
};

export const getMappingVersion = async (
  projectId: string,
  versionId: string,
  options?: RequestInit,
): Promise<MappingVersionResponse> => {
  return customFetch<MappingVersionResponse>(
    getGetMappingVersionUrl(projectId, versionId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetMappingVersionQueryKey = (
  projectId: string,
  versionId: string,
) => {
  return [`/projects/${projectId}/mappings/${versionId}`] as const;
};

export const getGetMappingVersionQueryOptions = <
  TData = Awaited<ReturnType<typeof getMappingVersion>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  versionId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMappingVersion>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetMappingVersionQueryKey(projectId, versionId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMappingVersion>>
  > = ({ signal }) =>
    getMappingVersion(projectId, versionId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(projectId && versionId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMappingVersion>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMappingVersionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMappingVersion>>
>;
export type GetMappingVersionQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary Get Mapping Version
 */

export function useGetMappingVersion<
  TData = Awaited<ReturnType<typeof getMappingVersion>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  versionId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMappingVersion>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMappingVersionQueryOptions(
    projectId,
    versionId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Validate a mapping version against pinned schemas with optional policy overrides.
 * @summary Validate Mapping
 */
export const getValidateMappingUrl = (projectId: string) => {
  return `/projects/${projectId}/validate`;
};

export const validateMapping = async (
  projectId: string,
  validateRequest: ValidateRequest,
  options?: RequestInit,
): Promise<ValidationResponse> => {
  return customFetch<ValidationResponse>(getValidateMappingUrl(projectId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(validateRequest),
  });
};

export const getValidateMappingMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validateMapping>>,
    TError,
    { projectId: string; data: BodyType<ValidateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validateMapping>>,
  TError,
  { projectId: string; data: BodyType<ValidateRequest> },
  TContext
> => {
  const mutationKey = ["validateMapping"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validateMapping>>,
    { projectId: string; data: BodyType<ValidateRequest> }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return validateMapping(projectId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidateMappingMutationResult = NonNullable<
  Awaited<ReturnType<typeof validateMapping>>
>;
export type ValidateMappingMutationBody = BodyType<ValidateRequest>;
export type ValidateMappingMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Validate Mapping
 */
export const useValidateMapping = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validateMapping>>,
    TError,
    { projectId: string; data: BodyType<ValidateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof validateMapping>>,
  TError,
  { projectId: string; data: BodyType<ValidateRequest> },
  TContext
> => {
  return useMutation(getValidateMappingMutationOptions(options));
};

/**
 * Export a mapping artifact as deterministic JSON.
 * @summary Export Mapping
 */
export const getExportMappingUrl = (
  projectId: string,
  params: ExportMappingParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/projects/${projectId}/export?${stringifiedParams}`
    : `/projects/${projectId}/export`;
};

export const exportMapping = async (
  projectId: string,
  params: ExportMappingParams,
  options?: RequestInit,
): Promise<ExportResponse> => {
  return customFetch<ExportResponse>(getExportMappingUrl(projectId, params), {
    ...options,
    method: "POST",
  });
};

export const getExportMappingMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof exportMapping>>,
    TError,
    { projectId: string; params: ExportMappingParams },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof exportMapping>>,
  TError,
  { projectId: string; params: ExportMappingParams },
  TContext
> => {
  const mutationKey = ["exportMapping"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof exportMapping>>,
    { projectId: string; params: ExportMappingParams }
  > = (props) => {
    const { projectId, params } = props ?? {};

    return exportMapping(projectId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExportMappingMutationResult = NonNullable<
  Awaited<ReturnType<typeof exportMapping>>
>;

export type ExportMappingMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Export Mapping
 */
export const useExportMapping = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof exportMapping>>,
    TError,
    { projectId: string; params: ExportMappingParams },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof exportMapping>>,
  TError,
  { projectId: string; params: ExportMappingParams },
  TContext
> => {
  return useMutation(getExportMappingMutationOptions(options));
};

// ---------------------------------------------------------------------------
// Catalog browse
// ---------------------------------------------------------------------------

/**
 * @summary List Catalog Schemas
 */
export const getListCatalogSchemasUrl = (params?: ListCatalogSchemasParams) => {
  const searchParams = new URLSearchParams();
  if (params?.type != null) searchParams.set("type", params.type);
  if (params?.format != null) searchParams.set("format", params.format);
  if (params?.status != null) searchParams.set("status", params.status);
  if (params?.q != null) searchParams.set("q", params.q);
  const qs = searchParams.toString();
  return `/catalog/schemas${qs ? `?${qs}` : ""}`;
};

export const listCatalogSchemas = async (
  params?: ListCatalogSchemasParams,
  options?: RequestInit,
): Promise<CatalogSchemaResponse[]> => {
  return customFetch<CatalogSchemaResponse[]>(getListCatalogSchemasUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListCatalogSchemasQueryKey = (params?: ListCatalogSchemasParams) => {
  return [`/catalog/schemas`, ...(params ? [params] : [])] as const;
};

export const getListCatalogSchemasQueryOptions = <
  TData = Awaited<ReturnType<typeof listCatalogSchemas>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params?: ListCatalogSchemasParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof listCatalogSchemas>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getListCatalogSchemasQueryKey(params);
  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCatalogSchemas>>> = ({ signal }) =>
    listCatalogSchemas(params, { signal, ...requestOptions });
  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCatalogSchemas>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCatalogSchemasQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCatalogSchemas>>
>;
export type ListCatalogSchemasQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary List Catalog Schemas
 */
export function useListCatalogSchemas<
  TData = Awaited<ReturnType<typeof listCatalogSchemas>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params?: ListCatalogSchemasParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof listCatalogSchemas>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCatalogSchemasQueryOptions(params, options);
  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };
  query.queryKey = queryOptions.queryKey;
  return query;
}

/**
 * @summary List Schema Versions
 */
export const getListSchemaVersionsUrl = (schemaId: string) => {
  return `/catalog/schemas/${schemaId}/versions`;
};

export const listSchemaVersions = async (
  schemaId: string,
  options?: RequestInit,
): Promise<CatalogVersionResponse[]> => {
  return customFetch<CatalogVersionResponse[]>(getListSchemaVersionsUrl(schemaId), {
    ...options,
    method: "GET",
  });
};

export const getListSchemaVersionsQueryKey = (schemaId: string) => {
  return [`/catalog/schemas/${schemaId}/versions`] as const;
};

export const getListSchemaVersionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listSchemaVersions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  schemaId: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof listSchemaVersions>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getListSchemaVersionsQueryKey(schemaId);
  const queryFn: QueryFunction<Awaited<ReturnType<typeof listSchemaVersions>>> = ({ signal }) =>
    listSchemaVersions(schemaId, { signal, ...requestOptions });
  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSchemaVersions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListSchemaVersionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSchemaVersions>>
>;
export type ListSchemaVersionsQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary List Schema Versions
 */
export function useListSchemaVersions<
  TData = Awaited<ReturnType<typeof listSchemaVersions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  schemaId: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof listSchemaVersions>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListSchemaVersionsQueryOptions(schemaId, options);
  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };
  query.queryKey = queryOptions.queryKey;
  return query;
}
