/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * v1 REST API for the Healthcare Data Mapping Tool.
Auth: Pass X-User-Id and X-User-Role headers with every request.
Roles: viewer, analyst, approver, admin.

 * OpenAPI spec version: 1.0.0
 */
export interface CreateProjectRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  sensitivity?: string | null;
}

export interface UpdateProjectStatusRequest {
  /** Target status. Allowed: draft, review, approved, published, archived */
  status: string;
}

export interface ProjectResponse {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  status: string;
  owner: string;
  sensitivity: string;
  created_at: string;
}

export interface ImportSourceSchemaRequest {
  /** Adapter format identifier. Examples: json_schema, csv_schema. */
  format_id: string;
  /** @minLength 1 */
  schema_name: string;
  /** @minLength 1 */
  version_label: string;
  schema_payload: unknown;
  /** @nullable */
  notes?: string | null;
}

export interface SelectTargetSchemaRequest {
  /** Catalog schema_id of the schema to pin as target. */
  schema_id: string;
  /** @minLength 1 */
  version_label: string;
}

export interface PinnedSchemaRef {
  pin_id: string;
  schema_id: string;
  version_label: string;
  schema_name: string;
  format_id: string;
  field_count: number;
}

export interface ProjectSchemasResponse {
  project_id: string;
  source: PinnedSchemaRef | null;
  target: PinnedSchemaRef | null;
}

export interface SuggestionsRequest {
  /**
   * @minimum 1
   * @maximum 50
   */
  top_k?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  min_confidence?: number;
}

export interface SuggestionCandidateDTO {
  source_field_ids: string[];
  source_field_paths: string[];
  confidence: number;
  reasons: string[];
  warnings: string[];
}

export interface FieldSuggestionsDTO {
  target_field_id: string;
  target_field_path: string;
  candidates: SuggestionCandidateDTO[];
}

export interface SourceFieldRef {
  id: string;
  path: string;
}

export interface SuggestionsResponse {
  project_id: string;
  source_schema_id: string;
  target_schema_id: string;
  field_suggestions: FieldSuggestionsDTO[];
  source_fields: SourceFieldRef[];
}

export interface TransformHintDTO {
  kind?: string;
  /** @nullable */
  expression?: string | null;
}

export interface MappingRuleDTO {
  target_field_id: string;
  source_field_ids?: string[];
  transform?: TransformHintDTO;
  /** @nullable */
  default_value?: string | null;
  /** @nullable */
  constant_value?: string | null;
  /** @nullable */
  notes?: string | null;
}

export interface CreateMappingVersionRequest {
  /** @minLength 1 */
  version_label: string;
  rules: MappingRuleDTO[];
  /** @nullable */
  notes?: string | null;
}

export interface UpdateMappingVersionRequest {
  rules: MappingRuleDTO[];
  /** @nullable */
  notes?: string | null;
}

export interface MappingVersionResponse {
  id: string;
  project_id: string;
  version_label: string;
  created_at: string;
  rule_count: number;
  /** @nullable */
  notes: string | null;
  rules?: MappingRuleDTO[];
}

export interface SeverityOverride {
  rule_id: string;
  /** error | warn | info */
  severity: string;
}

export interface ValidateRequest {
  mapping_version_id: string;
  severity_overrides?: SeverityOverride[];
}

export interface ValidationIssueDTO {
  rule_id: string;
  severity: string;
  message: string;
  affected_field_ids: string[];
  affected_field_paths: string[];
  /** @nullable */
  remediation_hint: string | null;
}

export interface ValidationResponse {
  project_id: string;
  mapping_version_id: string;
  has_errors: boolean;
  error_count: number;
  warning_count: number;
  issues: ValidationIssueDTO[];
}

export interface ExportResponse {
  project_id: string;
  mapping_version_id: string;
  /** Deterministic JSON export of the mapping artifact. */
  artifact_json: string;
  /** Placeholder. Script generation will be implemented in Phase 6. */
  transformation_script?: string;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type XUserIdParameter = string;

export type XUserRoleParameter = string;

export type ExportMappingParams = {
  mapping_version_id: string;
};

export interface CatalogSchemaResponse {
  /** Schema identifier in the catalog. */
  id: string;
  name: string;
  /** Open adapter format identifier. */
  format_id: string;
  /** 'custom' or 'standard'. */
  schema_type: string;
  /** 'draft' or 'approved'. */
  approval_status: string;
  owner: string;
  /** @nullable */
  description: string | null;
  /** Version label of the most recently registered version. @nullable */
  latest_version_label: string | null;
  /** Total number of registered versions for this schema. */
  available_versions_count: number;
  created_at: string;
  metadata_tags: Record<string, string>;
}

export interface CatalogVersionResponse {
  /** Version UUID. */
  id: string;
  schema_id: string;
  version_label: string;
  created_at: string;
  /** SHA-256 content fingerprint. */
  checksum: string;
  /** @nullable */
  notes: string | null;
}

export type ListCatalogSchemasParams = {
  type?: string;
  format?: string;
  status?: string;
  q?: string;
};
