"""FastAPI application factory for the v1 API.

Composes all routers and configures global middleware.
OpenAPI spec is auto-generated by FastAPI at /openapi.json.
"""

from __future__ import annotations

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from apps.api.routers import catalog, export, mappings, projects, schemas, suggestions, validation

_APP_TITLE = "Healthcare Data Mapping Tool API"
_APP_VERSION = "1.0.0"
_APP_DESCRIPTION = """
v1 REST API for the Healthcare Data Mapping Tool.

## Auth (v1 simulated RBAC)
Pass `X-User-Id` and `X-User-Role` headers with every request.
Roles: `viewer`, `analyst`, `approver`, `admin`.

## Phase scope
- Schema import + catalog (Phase 3)
- Mapping suggestions (Phase 4)
- Mapping validation with configurable policy (Phase 4)
- Mapping artifact export (Phase 6 script placeholder)

## Out of scope for v1
- Transformation execution (Phase 6)
- Patient-level data ingestion (forbidden in v1)
"""


def create_app() -> FastAPI:
    app = FastAPI(
        title=_APP_TITLE,
        version=_APP_VERSION,
        description=_APP_DESCRIPTION,
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
    )

    # ---------------------------------------------------------------------------
    # Middleware
    # ---------------------------------------------------------------------------
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ---------------------------------------------------------------------------
    # Routers
    # ---------------------------------------------------------------------------
    app.include_router(projects.router)
    app.include_router(schemas.router)
    app.include_router(suggestions.router)
    app.include_router(mappings.router)
    app.include_router(validation.router)
    app.include_router(export.router)
    app.include_router(catalog.router)

    # ---------------------------------------------------------------------------
    # Global error handlers
    # ---------------------------------------------------------------------------

    @app.exception_handler(Exception)
    async def unhandled_exception_handler(
        request: Request, exc: Exception
    ) -> JSONResponse:
        # Never leak stack traces in production response bodies.
        # Logged server-side (replace with structured logging in v2).
        return JSONResponse(
            status_code=500,
            content={"detail": "Internal server error."},
        )

    return app


# Top-level app instance (uvicorn/gunicorn entry point)
app = create_app()
